version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yml --config-file samconfig.toml --s3-bucket $S3_BUCKET --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
    - config.json