AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Rotates IP Address of VPN server
Parameters:
  HostedZone:
    Description: 'Hosted zone id on Route 53'
    Type: String
  InstanceId:
    Description: 'EC2 instance id'
    Type: String
  SnsTopic:
    Description: 'SNS topic for sending out error messages'
    Type: String
  IamRole:
    Description: 'IAM role for the lambda function'
    Type: String
Resources:
  Whirlwind:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          HOSTED_ZONE_ID: !Ref HostedZone
          INSTANCE_ID: !Ref InstanceId
          SNS_TOPIC: !Ref SnsTopic
      Handler: whirlwind.lambda_handler
      FunctionName: whirlwind
      PackageType: Zip
      Runtime: python3.8
      CodeUri: ./src
      Timeout: 7
      Role: !Ref IamRole
  DailyTrigger:
    Type: AWS::Events::Rule
    Properties: 
      Description: "Nightly IP address rotation"
      Name: "nightly-rotate-ip-address"
      ScheduleExpression: "cron(0 7 * * ? *)"
      Targets: 
        - Arn: !GetAtt Whirlwind.Arn
          Id: "Whirlwind"
 